name: Deploy to Ubuntu Server

on:
  push:
    branches:
      - develop

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add remote server to known hosts
        run: |
          mkdir -p ~/.ssh/
          ssh-keyscan ${{ secrets.REMOTE_HOST }} >> ~/.ssh/known_hosts

      - name: Copy files via SSH
        run: |
          scp -r ./* ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}:/home/${{ secrets.REMOTE_USER }}/app/

      - name: Deploy application
        run: |
          ssh ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} << 'EOF'
            cd /home/${{ secrets.REMOTE_USER }}/app
            # Optional: Add your application build commands here
            ./gradlew build
            cp ../application-dev.properties src/main/resources/application.properties 
            cp build/libs/grh-website-0.0.1-SNAPSHOT.jar my-app.jar

            # Restarting the service for all
            sudo systemctl restart myapp.service